In [66]:
from sklearn.datasets import load_digits
digits = load_digits()
print(digits.data.shape)

(1797, 64)


In [67]:
digits.data

array([[ 0.,  0.,  5., ...,  0.,  0.,  0.],
       [ 0.,  0.,  0., ..., 10.,  0.,  0.],
       [ 0.,  0.,  0., ..., 16.,  9.,  0.],
       ...,
       [ 0.,  0.,  1., ...,  6.,  0.,  0.],
       [ 0.,  0.,  2., ..., 12.,  0.,  0.],
       [ 0.,  0., 10., ..., 12.,  1.,  0.]])

In [68]:
digits.target

array([0, 1, 2, ..., 8, 9, 8])

In [69]:
from sklearn import  tree 
import numpy as np

In [70]:
clf = tree.DecisionTreeClassifier(random_state=1)
clf.fit(digits.data, digits.target) 

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=1, splitter='best')

In [71]:
from sklearn.model_selection import cross_val_score
from sklearn import metrics
scores = cross_val_score(clf, digits.data, digits.target, cv=10, scoring='f1_macro')

In [72]:
scores

array([0.79986396, 0.8418723 , 0.80635258, 0.80571118, 0.78722784,
       0.90077658, 0.90229943, 0.81584475, 0.83530487, 0.78856818])

In [73]:
scores.mean()

0.8283821672604125

In [74]:
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier
q = BaggingClassifier(DecisionTreeClassifier(),n_estimators = 100)

In [75]:
print(q)

BaggingClassifier(base_estimator=DecisionTreeClassifier(class_weight=None,
                                                        criterion='gini',
                                                        max_depth=None,
                                                        max_features=None,
                                                        max_leaf_nodes=None,
                                                        min_impurity_decrease=0.0,
                                                        min_impurity_split=None,
                                                        min_samples_leaf=1,
                                                        min_samples_split=2,
                                                        min_weight_fraction_leaf=0.0,
                                                        presort=False,
                                                        random_state=None,
                                                        splitter='best'),
    

In [81]:
scores = cross_val_score(q, digits.data, digits.target, cv=10, scoring='f1_macro')

In [82]:
scores

array([0.86410463, 0.95097607, 0.89869259, 0.93326529, 0.92130316,
       0.97773829, 0.97140132, 0.9068743 , 0.85696963, 0.91304612])

In [83]:
scores.mean()

0.9194371401503145

In [84]:
digits.data.shape[1]

64

In [111]:
qq = BaggingClassifier(DecisionTreeClassifier(),n_estimators = 100, max_features=int(np.sqrt(digits.data.shape[1])))

In [112]:
scores = cross_val_score(qq, digits.data, digits.target, cv=10, scoring='f1_macro')

In [113]:
scores

array([0.90572539, 0.94898677, 0.9308865 , 0.89283962, 0.92312937,
       0.93298415, 0.94181193, 0.97124132, 0.91469968, 0.9138245 ])

In [114]:
scores.mean()

0.9276129240905304

In [115]:
qqq = BaggingClassifier(DecisionTreeClassifier(max_features=int(np.sqrt(digits.data.shape[1]))),n_estimators = 100)

In [116]:
scores = cross_val_score(qqq, digits.data, digits.target, cv=10, scoring='f1_macro')

In [117]:
scores

array([0.90605401, 0.97781138, 0.95003495, 0.93907571, 0.94843522,
       0.98312148, 0.96580037, 0.9648475 , 0.92130192, 0.93607196])

In [118]:
scores.mean()

0.9492554503229055

In [119]:
from sklearn.ensemble import RandomForestClassifier

In [153]:
ww = RandomForestClassifier(n_estimators=100,random_state=0, max_depth=5)
ww.fit(digits.data, digits.target)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=5, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [154]:
scores = cross_val_score(ww, digits.data, digits.target, cv=10, scoring='f1_macro')

In [155]:
scores

array([0.85118643, 0.94975392, 0.88824089, 0.90497765, 0.92546228,
       0.95028591, 0.95446116, 0.9474424 , 0.84812649, 0.87092249])

In [156]:
scores.mean()

0.9090859626243608